//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class APODERADO
    {
        public APODERADO()
        {
            this.ALUMNOS = new HashSet<ALUMNO>();
            this.PAGOS = new HashSet<PAGO>();
        }
    
        public decimal APODERADOS_ID { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<ALUMNO> ALUMNOS { get; set; }
        public virtual ICollection<PAGO> PAGOS { get; set; }
    }
}
