//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO
    {
        public ENCARGADO()
        {
            this.CURSOS = new HashSet<CURSO>();
            this.PAGOS = new HashSet<PAGO>();
        }
    
        public decimal ENCARGADOS_ID { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string TELEFONO { get; set; }
        public decimal AGENTE_AGENTE_ID { get; set; }
    
        public virtual AGENTE AGENTE { get; set; }
        public virtual ICollection<CURSO> CURSOS { get; set; }
        public virtual ICollection<PAGO> PAGOS { get; set; }
    }
}
