//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS_ADICIONALES
    {
        public decimal SERVICIOS_ID { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public string TIPO { get; set; }
        public decimal CONTRATOS_CONTRATOS_ID { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
