//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        public TOUR()
        {
            this.ACTIVIDADES_TOUR = new HashSet<ACTIVIDADES_TOUR>();
            this.CONTRATOS = new HashSet<CONTRATO>();
        }
    
        public decimal TOURS_ID { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO_BASE { get; set; }
        public decimal DIAS { get; set; }
        public decimal DESTINOS_DESTINOS_ID { get; set; }
        public decimal PRECIO_TOTAL { get; set; }
        public decimal POLIZAS_POLIZAS_ID { get; set; }
    
        public virtual ICollection<ACTIVIDADES_TOUR> ACTIVIDADES_TOUR { get; set; }
        public virtual ICollection<CONTRATO> CONTRATOS { get; set; }
        public virtual DESTINO DESTINO { get; set; }
        public virtual POLIZA POLIZA { get; set; }
    }
}
